/*
	Strategy
	Authors: ChimpanG
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType								)
VALUES 	('LEADER_CVS_STEPHEN_III_TECHS'			),
		('LEADER_CVS_STEPHEN_III_CIVICS'		),
		('LEADER_CVS_STEPHEN_III_DISTRICTS'		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS'		),
		('LEADER_CVS_STEPHEN_III_PROJECTS'		),
		('LEADER_CVS_STEPHEN_III_DIPLOMACY'		),
		('LEADER_CVS_STEPHEN_III_TACTICS'		),
		('LEADER_CVS_STEPHEN_III_EXPANSION'		),
		('LEADER_CVS_STEPHEN_III_PSUEDOS'		),
		('LEADER_CVS_STEPHEN_III_YIELDS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,								LeaderType,						System				)
VALUES  ('LEADER_CVS_STEPHEN_III_TECHS',		'TRAIT_LEADER_CVS_STEPHEN_III',	'Technologies'		),
		('LEADER_CVS_STEPHEN_III_CIVICS',		'TRAIT_LEADER_CVS_STEPHEN_III',	'Civics'			),
		('LEADER_CVS_STEPHEN_III_DISTRICTS',	'TRAIT_LEADER_CVS_STEPHEN_III',	'Districts'			),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',	'TRAIT_LEADER_CVS_STEPHEN_III',	'Buildings'			),
		('LEADER_CVS_STEPHEN_III_PROJECTS',		'TRAIT_LEADER_CVS_STEPHEN_III',	'Projects'			),
		('LEADER_CVS_STEPHEN_III_DIPLOMACY',	'TRAIT_LEADER_CVS_STEPHEN_III',	'DiplomaticActions'	),
		('LEADER_CVS_STEPHEN_III_TACTICS',		'TRAIT_LEADER_CVS_STEPHEN_III',	'Tactics'			),
		('LEADER_CVS_STEPHEN_III_EXPANSION',	'TRAIT_LEADER_CVS_STEPHEN_III',	'PlotEvaluations'	),
		('LEADER_CVS_STEPHEN_III_PSUEDOS',		'TRAIT_LEADER_CVS_STEPHEN_III',	'PsuedoYields'		),
		('LEADER_CVS_STEPHEN_III_YIELDS',		'TRAIT_LEADER_CVS_STEPHEN_III',	'Yields'			);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,									Item,										Favored	)
VALUES  -- TECHS
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_BRONZE_WORKING',						1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_MASONRY',								1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_CASTLES',								1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_MILITARY_ENGINEERING',				1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_SIEGE_TACTICS',						1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_INDUSTRIALIZATION',					1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_REPLACEABLE_PARTS',					1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_FLIGHT',								1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_STEEL',								1		),
		('LEADER_CVS_STEPHEN_III_TECHS',			'TECH_ASTROLOGY',							1		),
		-- CIVICS
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_MEDIEVAL_FAIRES',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_MILITARY_TRADITION',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_EARLY_EMPIRE',						1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_MILITARY_TRAINING',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_NATIONALISM',						1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_DEFENSIVE_TACTICS',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_MERCENARIES',						1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_DIPLOMATIC_SERVICE',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_MERCANTILISM',						1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_CONSERVATION',						1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_MASS_MEDIA',							1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_SUFFRAGE',							1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_CLASS_STRUGGLE',						1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_TOTALITARIANISM',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_RAPID_DEPLOYMENT',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_CULTURAL_HERITAGE',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_CIVIL_ENGINEERING',					1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_DRAMA_POETRY',						1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_OPERA_BALLET',						1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_THEOLOGY',							1		),
		('LEADER_CVS_STEPHEN_III_CIVICS',			'CIVIC_DIVINE_RIGHT',						1		),
		-- DISTRICTS
		('LEADER_CVS_STEPHEN_III_DISTRICTS',		'DISTRICT_ENCAMPMENT',						1		),
		('LEADER_CVS_STEPHEN_III_DISTRICTS',		'DISTRICT_HOLY_SITE',						1		),
		('LEADER_CVS_STEPHEN_III_DISTRICTS',		'DISTRICT_THEATER',							1		),
		-- BUILDINGS
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_BARRACKS',						1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_ARMORY',							1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_MILITARY_ACADEMY',				1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_WALLS',							1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_CASTLE',							1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_STAR_FORT',						1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_SHRINE',							1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_TEMPLE',							1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_CVS_STEPHEN_III_UI',				1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_AMPHITHEATER',					1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_MUSEUM_ART',						1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_MUSEUM_ARTIFACT',					0		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_BROADCAST_CENTER',				1		),
		-- WONDERS
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_ALHAMBRA',						1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_FORBIDDEN_CITY',					1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_RUHR_VALLEY',						1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_TAJ_MAHAL',						1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_TERRACOTTA_ARMY',					1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_BOLSHOI_THEATER',					1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_STONEHENGE',						1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_SYDNEY_OPERA_HOUSE',				1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_ORACLE',							1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_MAHABODHI_TEMPLE',				1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_HERMITAGE',						1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_CRISTO_REDENTOR',					1		),
		('LEADER_CVS_STEPHEN_III_BUILDINGS',		'BUILDING_BROADWAY',						1		);
		
INSERT INTO AiFavoredItems
		(ListType,								Item,								Favored,	Value,	StringVal					)
VALUES  -- EXPANSION
		('LEADER_CVS_STEPHEN_III_EXPANSION',	'Specific Feature',					1,			7,		'FEATURE_FOREST'			),
		-- PSUEDOS
		('LEADER_CVS_STEPHEN_III_PSUEDOS',		'PSEUDOYIELD_GPP_GENERAL',			1,			15,		NULL						),
		('LEADER_CVS_STEPHEN_III_PSUEDOS',		'PSEUDOYIELD_GPP_ARTIST',			1,			30,		NULL						),
		('LEADER_CVS_STEPHEN_III_PSUEDOS',		'PSEUDOYIELD_GPP_PROPHET',			1,			30,		NULL						),
		('LEADER_CVS_STEPHEN_III_PSUEDOS',		'PSEUDOYIELD_GPP_WRITER',			1,			10,		NULL						),
		('LEADER_CVS_STEPHEN_III_PSUEDOS',		'PSEUDOYIELD_GPP_MUSICIAN',			1,			10,		NULL						),
		('LEADER_CVS_STEPHEN_III_PSUEDOS',		'PSEUDOYIELD_IMPROVEMENT',			1,			5,		NULL						),
		('LEADER_CVS_STEPHEN_III_PSUEDOS',		'PSEUDOYIELD_UNIT_COMBAT',			1,			20,		NULL						);
